application: google.com:slowreports

includes:
- mapreduce/include.yaml

version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /upload
  script: main.app

- url: /_ah/pipeline.*
  script: mapreduce.lib.pipeline.handlers._APP
  login: admin

