application: google.com:slowreports

includes:
- mapreduce/include.yaml

indexes:
- kind: _AE_Pipeline_Record
  properties:
  - name: is_root_pipeline
  - name: start_time
    direction: desc
- kind: _AE_Pipeline_Record
  properties:
  - name: class_path
  - name: start_time
    direction: desc

version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /upload
  script: main.app

- url: /_ah/pipeline.*
  script: mapreduce.lib.pipeline.handlers._APP
  login: admin

